# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_article_head_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to='uploads', verbose_name='\u6587\u7ae0\u6807\u9898\u56fe\u7247'),
        ),
    ]
