# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-29 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20171029_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.IntegerField(choices=[(1, '\u8bc4\u8bba'), (2, '\u70b9\u8d5e')], default=1),
        ),
    ]
